### ISSUE TITLE
After importing 3rd account, Vessel is blank

### ISSUE THREAD

**Issue by noisy** [aaroncox/vessel#10] opened 2017-05-25 06:06 UTC
I do not have any logs, so I cannot give you right now more details.

![selection_999 070](https://cloud.githubusercontent.com/assets/201263/26438049/ed422380-4120-11e7-8247-da5969916375.png)

OS: Ubuntu 14.04

**Comment by aaroncox** [comment] 2017-05-25 06:09
Hrm - CTRL+R will refresh the app (since it's a web browser), that might fix it. 

You should also be able to open up the chrome console through the menu's, though I'm not absolutely sure how via Ubuntu. 

`F12`, `Ctrl + Shift + I` or `Cmd + Opt + I` maybe?

**Comment by noisy** [comment] 2017-05-25 06:10
I tried to reinstall vessel, but so far without a success. Where vessel keeps the data, that I could remove everything and setup everything from the scratch?

**Comment by aaroncox** [comment] 2017-05-25 06:11
Mac OS: ~/Library/Application Support/vessel
Windows: C:\Users\<you>\AppData\Local\vessel
Linux: ~/.config/vessel

**Comment by noisy** [comment] 2017-05-25 06:12
refresh doesn't help in my case

**Comment by aaroncox** [comment] 2017-05-25 06:12
Can you get the dev tools open?

**Comment by noisy** [comment] 2017-05-25 06:15
Good information. After removing `~/.config/vessel` it works again. Bad information, I didn't notice your comment, so I removed a folder before I tried to open dev tools.

**Comment by aaroncox** [comment] 2017-05-25 06:18
haha, no worries. That's where it's all stored. From the sounds of it, it sounds like something got imported and it didn't know how to handle it on load. If you're able to reproduce, and can get the devtools open, let me know what was causing it and I'll get it fixed.

**Comment by noisy** [comment] 2017-05-25 06:21
I try to open dev tools in a way how I do it on Chrome (Ctrl + Shift + I). But it doesn't work in an app :/

**Comment by aaroncox** [comment] 2017-05-25 06:22
Hrm - I'll have to look into that.

**Comment by aaroncox** [comment] 2017-05-25 06:25
We safe to close this one unless it crops up again??

**Comment by aaroncox** [comment] 2017-05-25 06:32
Opened #11 in relation to the devtools not opening

**Comment by aaroncox** [comment] 2017-05-29 00:03
DevTools should be enabled now in 0.0.6-c. If you run into any errors, open up the console and let me know what error is being thrown.

**Closed by aaroncox** 2017-05-29 00:03 UTC
